version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - ./:/app

  redis:
    image: "redis"
    volumes:
      - redis:/var/lib/redis
    ports:
      - "6379:6379"
    links:
      - redis-commander

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379

volumes:
  redis: