version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - redis

  redis:
    image: "redis"
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    privileged: true
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  redis-insight:
    image: redislabs/redisinsight:1.14.0
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - redis-insight-volume:/db
    depends_on:
      - redis

volumes:
  redis-insight-volume:
