version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - redis

  redis:
    image: "redis"
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    privileged: true
    links:
      - redis-commander
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
